import { Link } from "react-router";
import { ArrowRight, BarChart3, BookOpen, Brain, CheckCircle2, FileText, ShieldCheck, Sparkles, Target } from "lucide-react";
import { Button } from "../ui/button";

const features = [
  { icon: Sparkles, title: "Generate with confidence", description: "Create well-structured assessment questions from your syllabus in minutes." },
  { icon: Target, title: "Balance Bloom's levels", description: "Make cognitive coverage visible before a paper reaches moderation." },
  { icon: BarChart3, title: "See curriculum coverage", description: "Use clear analytics to spot gaps and improve every assessment cycle." },
];

function Brand({ inverted = false }: { inverted?: boolean }) {
  return <div className="flex items-center gap-2"><span className="grid size-10 place-items-center rounded-xl bg-primary text-primary-foreground shadow-sm"><Brain className="size-6" /></span><span className={`text-xl font-bold tracking-tight ${inverted ? "text-white" : "text-foreground"}`}>GenQGen</span></div>;
}

export function LandingPage() {
  return <main className="min-h-screen overflow-x-hidden bg-background text-foreground">
    <header className="sticky top-0 z-20 border-b border-border/70 bg-background/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between gap-5 px-5 py-3 sm:px-8"><Link to="/" aria-label="GenQGen home"><Brand /></Link><nav className="hidden items-center gap-6 text-sm text-muted-foreground md:flex" aria-label="Main navigation"><a className="hover:text-foreground" href="#features">Features</a><a className="hover:text-foreground" href="#workflow">How it works</a><a className="hover:text-foreground" href="#security">Security</a></nav><div className="flex items-center gap-2"><Button asChild variant="ghost" className="hidden sm:inline-flex"><Link to="/login">Sign in</Link></Button><Button asChild><Link to="/register">Get started <ArrowRight /></Link></Button></div></div></header>
    <section className="relative isolate overflow-hidden"><div className="absolute inset-x-0 top-0 -z-10 h-[38rem] bg-[radial-gradient(circle_at_75%_15%,color-mix(in_srgb,var(--secondary)_20%,transparent),transparent_34%),radial-gradient(circle_at_20%_25%,color-mix(in_srgb,var(--primary)_18%,transparent),transparent_36%)]" /><div className="mx-auto grid max-w-7xl gap-14 px-5 py-20 sm:px-8 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:py-28"><div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-3 py-1.5 text-sm font-medium text-primary"><Sparkles className="size-4" /> AI-powered academic assessment</div><h1 className="max-w-3xl text-4xl font-bold leading-tight tracking-tight sm:text-5xl lg:text-6xl">Better question papers, built around better learning.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">GenQGen helps educators generate, review, and analyze assessments that align with their syllabus and Bloom&apos;s Taxonomy.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg"><Link to="/register">Create your account <ArrowRight /></Link></Button><Button asChild variant="outline" size="lg"><Link to="/login">Sign in to GenQGen</Link></Button></div><div className="mt-8 flex flex-wrap gap-x-5 gap-y-3 text-sm text-muted-foreground">{["Syllabus-aware generation", "Bloom's level coverage", "Faculty-ready review"].map(item => <span className="flex items-center gap-2" key={item}><CheckCircle2 className="size-4 text-success" />{item}</span>)}</div></div><QuestionPaperPreview /></div></section>
    <section id="features" className="border-y border-border bg-muted/35 py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8"><p className="text-center text-sm font-semibold uppercase tracking-widest text-primary">Purpose-built for educators</p><h2 className="mx-auto mt-3 max-w-2xl text-center text-3xl font-bold tracking-tight">Everything needed to create thoughtful assessments.</h2><div className="mt-12 grid gap-5 md:grid-cols-3">{features.map(({ icon: Icon, title, description }) => <article className="rounded-2xl border border-border bg-card p-6 shadow-sm" key={title}><span className="grid size-11 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="size-5" /></span><h3 className="mt-5 text-lg font-semibold">{title}</h3><p className="mt-2 leading-7 text-muted-foreground">{description}</p></article>)}</div></div></section>
    <section id="workflow" className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="grid gap-10 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-widest text-secondary">A clear workflow</p><h2 className="mt-3 text-3xl font-bold tracking-tight">From syllabus to a paper your team can trust.</h2><p className="mt-5 leading-7 text-muted-foreground">Keep faculty in control at each stage: provide your syllabus, generate candidates, review the results, and use coverage analytics to refine the final paper.</p></div><div className="grid gap-4 sm:grid-cols-3"><WorkflowStep icon={BookOpen} number="1" label="Add your syllabus" /><WorkflowStep icon={Sparkles} number="2" label="Generate questions" /><WorkflowStep icon={FileText} number="3" label="Review & export" /></div></div></section>
    <section id="security" className="bg-slate-950 px-5 py-20 text-white sm:px-8"><div className="mx-auto flex max-w-5xl flex-col items-center text-center"><span className="grid size-12 place-items-center rounded-xl bg-white/10"><ShieldCheck className="size-6 text-cyan-300" /></span><h2 className="mt-5 text-3xl font-bold">Designed for responsible academic work.</h2><p className="mt-4 max-w-2xl leading-7 text-slate-300">GenQGen gives educators a structured workspace for assessment design, review, and syllabus coverage—not an unchecked replacement for academic judgement.</p><Button asChild variant="secondary" size="lg" className="mt-8"><Link to="/register">Start with GenQGen <ArrowRight /></Link></Button></div></section>
    <footer className="border-t border-border px-5 py-8 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 text-sm text-muted-foreground sm:flex-row sm:items-center"><Brand /><p>© {new Date().getFullYear()} GenQGen. AI-powered assessment design.</p><div className="flex gap-4"><Link className="hover:text-foreground" to="/login">Sign in</Link><Link className="hover:text-foreground" to="/register">Sign up</Link></div></div></footer>
  </main>;
}

function QuestionPaperPreview() {
  const questions = [["Understand", "Explain Dijkstra’s shortest path algorithm.", "bg-warning/15 text-amber-800"], ["Apply", "Solve a 0/1 knapsack problem using dynamic programming.", "bg-success/15 text-emerald-800"], ["Analyze", "Compare greedy and dynamic programming approaches.", "bg-primary/15 text-primary"]];
  return <div className="relative mx-auto w-full max-w-xl rounded-2xl border border-border bg-card p-4 shadow-2xl shadow-primary/10"><div className="rounded-xl bg-gradient-to-br from-primary via-secondary to-accent p-5 text-white"><div className="flex items-center justify-between text-sm text-white/80"><span>CS401 · Advanced Algorithms</span><span>60 marks</span></div><h2 className="mt-6 text-2xl font-bold">Mid-Semester Assessment</h2><p className="mt-1 text-sm text-white/80">Balanced, syllabus-aligned, and ready for review.</p></div><div className="space-y-3 p-2 pt-5">{questions.map(([level, question, style], index) => <div className="rounded-xl border border-border p-4" key={level}><div className="flex items-start gap-3"><span className="font-semibold text-primary">Q{index + 1}</span><div><p className="text-sm font-medium leading-6">{question}</p><span className={`mt-2 inline-block rounded-md px-2 py-1 text-xs font-medium ${style}`}>{level}</span></div></div></div>)}</div></div>;
}

function WorkflowStep({ icon: Icon, number, label }: { icon: typeof BookOpen; number: string; label: string }) {
  return <div className="rounded-xl border border-border p-5"><Icon className="size-5 text-primary" /><p className="mt-5 text-sm text-muted-foreground">Step {number}</p><p className="mt-1 font-semibold">{label}</p></div>;
}
